name: Build and Push to ECR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Permission settings are required for OIDC (id-token: write)
permissions:
  id-token: write
  contents: read

env:
  DOCKER_BUILDKIT: 1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::851725310572:role/github_action"
          aws-region: "us-east-1"
          # This allows the action to assume the role using OIDC
          role-session-name: GitHubActionsECRPush

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4.0.0

      - name: Build and push
        uses: docker/build-push-action@v7.0.0
        with:
          context: .
          push: true
          # load to the local runner for Snyk to see
          load: true
          # Note how we use the output from the 'login-ecr' step
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/dev/flask-deploy:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/dev/flask-deploy:${{ github.ref_name }}-${{ github.run_number }}
          # This enables GHA caching for faster builds
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Snyk Container Scan (Remote)
        id: snyk-scan
        uses: snyk/actions/docker@master
        # We use 'continue-on-error' so we can trigger the delete step next
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ steps.login-ecr.outputs.registry }}/dev/flask-deploy:${{ github.sha }}
          args: --severity-threshold=high

      - name: Cleanup Failed Image from ECR
        # This only runs if the Snyk step found issues
        if: steps.snyk-scan.outcome == 'failure'
        run: |
          echo "Vulnerabilities found! Deleting image from ECR..."
          aws ecr batch-delete-image \
            --repository-name dev/flask-deploy \
            --image-ids imageTag=${{ github.sha }} imageTag=${{ github.ref_name }}-${{ github.run_number }}
          exit 1 # Still fail the whole job after cleanup

      
