name: Build and Push to Docker Images

on:
  push:
    branches:
    - main

env:
  REGISTRY: docker.io

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5.0.0
      
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3.11.1
      
    - name: Login Docker Hub
      uses: docker/login-action@v3.5.0
      with:
        username: ${{ secret.DOCKERHUB_USERNAME }}
        password: ${{ secret.DOCKERHUB_TOKEN }}
        
    - name: Build and Push Image
      uses: docker/build-push-action@v6.18.0
      with:
        # Tries to restore Docker layer cache from previous builds
        cache-from: type=gha
        # Saves the Docker layer cache for future builds
        cache-to: type=gha, mode=max
        # GHA stands for GitHub Actions Cache
        context: ./
        file: ./Dockerfile
        push: true
        platforms: ${{ matrix.platform }}
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/flask:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/flask:${{ github.sha }}
        
        
    
    
